// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Favorite struct {
	Uri        string
	Did        string
	SubjectUri string
	SubjectCid string
	CreatedAt  time.Time
}

type IngestState struct {
	Name  string
	Value string
}

type OauthRequest struct {
	State     string
	Data      []byte
	CreatedAt time.Time
}

type OauthSession struct {
	Did       string
	SessionID string
	Data      []byte
	UpdatedAt time.Time
}

type OgCard struct {
	Uri        string
	Version    string
	Png        []byte
	RenderedAt time.Time
}

type Profile struct {
	Did         string
	Handle      string
	DisplayName string
	Avatar      string
	Hidden      bool
	ResolvedAt  *time.Time
}

type Rating struct {
	Uri        string
	Did        string
	SubjectUri string
	SubjectCid string
	Value      int32
	CreatedAt  time.Time
}

type Sheet struct {
	Uri          string
	Did          string
	Rkey         string
	Cid          string
	Title        string
	Artist       string
	Album        string
	ArtistSlug   string
	TitleSlug    string
	Kind         string
	Key          string
	Capo         int32
	Tuning       string
	Difficulty   string
	Description  string
	Tags         []string
	TagsText     string
	Content      string
	Lyrics       string
	ForkOfUri    string
	ForkOfCid    string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IndexedAt    time.Time
	Names        pgtype.Text
	NamesCompact pgtype.Text
	Search       interface{}
	Voicings     []byte
	Draft        bool
}

type SheetStat struct {
	Uri           string
	RatingCount   int32
	RatingAvg     float64
	RatingScore   float64
	FavoriteCount int32
	ForkCount     int32
}

type SheetSummariesAll struct {
	Uri           string
	Did           string
	Rkey          string
	Cid           string
	Title         string
	Artist        string
	Album         string
	ArtistSlug    string
	TitleSlug     string
	Kind          string
	Key           string
	Capo          int32
	Tuning        string
	Difficulty    string
	Tags          []string
	ForkOfUri     string
	ForkOfCid     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Draft         bool
	Handle        string
	DisplayName   string
	Avatar        string
	RatingCount   int32
	RatingAvg     float64
	RatingScore   float64
	FavoriteCount int32
	ForkCount     int32
}

type SheetSummary struct {
	Uri           string
	Did           string
	Rkey          string
	Cid           string
	Title         string
	Artist        string
	Album         string
	ArtistSlug    string
	TitleSlug     string
	Kind          string
	Key           string
	Capo          int32
	Tuning        string
	Difficulty    string
	Tags          []string
	ForkOfUri     string
	ForkOfCid     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Draft         bool
	Handle        string
	DisplayName   string
	Avatar        string
	RatingCount   int32
	RatingAvg     float64
	RatingScore   float64
	FavoriteCount int32
	ForkCount     int32
}

type WebSession struct {
	Token     string
	Did       string
	SessionID string
	CreatedAt time.Time
}
