// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package dbq

import (
	"context"
	"time"
)

const accountSubjects = `-- name: AccountSubjects :many

SELECT r.subject_uri FROM ratings r WHERE r.did = $1::text
UNION SELECT f.subject_uri FROM favorites f WHERE f.did = $1::text
UNION SELECT s.fork_of_uri FROM sheets s WHERE s.did = $1::text AND s.fork_of_uri <> ''
`

// Accounts --------------------------------------------------------------
// Sheets whose stats an account's records feed into.
func (q *Queries) AccountSubjects(ctx context.Context, did string) ([]string, error) {
	rows, err := q.db.Query(ctx, accountSubjects, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var subject_uri string
		if err := rows.Scan(&subject_uri); err != nil {
			return nil, err
		}
		items = append(items, subject_uri)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const artistSheets = `-- name: ArtistSheets :many
SELECT uri, did, rkey, cid, title, artist, album, artist_slug, title_slug, kind, key, capo, tuning, difficulty, tags, fork_of_uri, fork_of_cid, created_at, updated_at, handle, display_name, avatar, rating_count, rating_avg, rating_score, favorite_count, fork_count FROM sheet_summaries WHERE artist_slug = $1 ORDER BY title_slug
`

func (q *Queries) ArtistSheets(ctx context.Context, artistSlug string) ([]SheetSummary, error) {
	rows, err := q.db.Query(ctx, artistSheets, artistSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SheetSummary{}
	for rows.Next() {
		var i SheetSummary
		if err := rows.Scan(
			&i.Uri,
			&i.Did,
			&i.Rkey,
			&i.Cid,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.ArtistSlug,
			&i.TitleSlug,
			&i.Kind,
			&i.Key,
			&i.Capo,
			&i.Tuning,
			&i.Difficulty,
			&i.Tags,
			&i.ForkOfUri,
			&i.ForkOfCid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Handle,
			&i.DisplayName,
			&i.Avatar,
			&i.RatingCount,
			&i.RatingAvg,
			&i.RatingScore,
			&i.FavoriteCount,
			&i.ForkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authorByDID = `-- name: AuthorByDID :one
SELECT did, handle, display_name, avatar FROM profiles WHERE did = $1 AND NOT hidden
`

type AuthorByDIDRow struct {
	Did         string
	Handle      string
	DisplayName string
	Avatar      string
}

func (q *Queries) AuthorByDID(ctx context.Context, did string) (AuthorByDIDRow, error) {
	row := q.db.QueryRow(ctx, authorByDID, did)
	var i AuthorByDIDRow
	err := row.Scan(
		&i.Did,
		&i.Handle,
		&i.DisplayName,
		&i.Avatar,
	)
	return i, err
}

const authorByHandle = `-- name: AuthorByHandle :one
SELECT did, handle, display_name, avatar FROM profiles WHERE handle = $1 AND NOT hidden
`

type AuthorByHandleRow struct {
	Did         string
	Handle      string
	DisplayName string
	Avatar      string
}

func (q *Queries) AuthorByHandle(ctx context.Context, handle string) (AuthorByHandleRow, error) {
	row := q.db.QueryRow(ctx, authorByHandle, handle)
	var i AuthorByHandleRow
	err := row.Scan(
		&i.Did,
		&i.Handle,
		&i.DisplayName,
		&i.Avatar,
	)
	return i, err
}

const cleanOAuthRequests = `-- name: CleanOAuthRequests :execrows
DELETE FROM oauth_requests WHERE created_at < $1
`

func (q *Queries) CleanOAuthRequests(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, cleanOAuthRequests, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanOAuthSessions = `-- name: CleanOAuthSessions :execrows
DELETE FROM oauth_sessions o
WHERE o.updated_at < $1
    AND NOT EXISTS (SELECT 1 FROM web_sessions w WHERE w.did = o.did AND w.session_id = o.session_id)
`

// OAuth sessions are only reachable through a browser session; once none
// points at one (signed out, expired) it's dead weight. updated_at gives a
// sign-in in progress time to create its browser session.
func (q *Queries) CleanOAuthSessions(ctx context.Context, updatedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, cleanOAuthSessions, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanOGCards = `-- name: CleanOGCards :execrows

DELETE FROM og_cards o
WHERE o.rendered_at < $1 OR NOT EXISTS (SELECT 1 FROM sheets s WHERE s.uri = o.uri)
`

// Cleanup (see Store.Cleanup) ---------------------------------------------
// Cards nobody has asked for in a while, or whose sheet is gone.
func (q *Queries) CleanOGCards(ctx context.Context, renderedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, cleanOGCards, renderedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanSheetStats = `-- name: CleanSheetStats :execrows
DELETE FROM sheet_stats st
WHERE st.rating_count = 0 AND st.favorite_count = 0 AND st.fork_count = 0
    AND NOT EXISTS (SELECT 1 FROM sheets s WHERE s.uri = st.uri)
`

// Stats for sheets that are gone and that nothing points at anymore.
func (q *Queries) CleanSheetStats(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanSheetStats)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cleanWebSessions = `-- name: CleanWebSessions :execrows
DELETE FROM web_sessions WHERE created_at < $1
`

func (q *Queries) CleanWebSessions(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, cleanWebSessions, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createWebSession = `-- name: CreateWebSession :exec
INSERT INTO web_sessions (token, did, session_id) VALUES ($1, $2, $3)
`

type CreateWebSessionParams struct {
	Token     string
	Did       string
	SessionID string
}

func (q *Queries) CreateWebSession(ctx context.Context, arg CreateWebSessionParams) error {
	_, err := q.db.Exec(ctx, createWebSession, arg.Token, arg.Did, arg.SessionID)
	return err
}

const deleteAccountFavorites = `-- name: DeleteAccountFavorites :exec
DELETE FROM favorites WHERE did = $1
`

func (q *Queries) DeleteAccountFavorites(ctx context.Context, did string) error {
	_, err := q.db.Exec(ctx, deleteAccountFavorites, did)
	return err
}

const deleteAccountOGCards = `-- name: DeleteAccountOGCards :exec
DELETE FROM og_cards WHERE starts_with(uri, 'at://' || $1::text || '/')
`

func (q *Queries) DeleteAccountOGCards(ctx context.Context, did string) error {
	_, err := q.db.Exec(ctx, deleteAccountOGCards, did)
	return err
}

const deleteAccountRatings = `-- name: DeleteAccountRatings :exec
DELETE FROM ratings WHERE did = $1
`

func (q *Queries) DeleteAccountRatings(ctx context.Context, did string) error {
	_, err := q.db.Exec(ctx, deleteAccountRatings, did)
	return err
}

const deleteAccountSheets = `-- name: DeleteAccountSheets :exec
DELETE FROM sheets WHERE did = $1
`

func (q *Queries) DeleteAccountSheets(ctx context.Context, did string) error {
	_, err := q.db.Exec(ctx, deleteAccountSheets, did)
	return err
}

const deleteFavorite = `-- name: DeleteFavorite :one
DELETE FROM favorites WHERE uri = $1 RETURNING subject_uri
`

func (q *Queries) DeleteFavorite(ctx context.Context, uri string) (string, error) {
	row := q.db.QueryRow(ctx, deleteFavorite, uri)
	var subject_uri string
	err := row.Scan(&subject_uri)
	return subject_uri, err
}

const deleteOAuthRequest = `-- name: DeleteOAuthRequest :exec
DELETE FROM oauth_requests WHERE state = $1
`

func (q *Queries) DeleteOAuthRequest(ctx context.Context, state string) error {
	_, err := q.db.Exec(ctx, deleteOAuthRequest, state)
	return err
}

const deleteOAuthRequestsBefore = `-- name: DeleteOAuthRequestsBefore :exec
DELETE FROM oauth_requests WHERE created_at < $1
`

func (q *Queries) DeleteOAuthRequestsBefore(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOAuthRequestsBefore, createdAt)
	return err
}

const deleteOAuthSession = `-- name: DeleteOAuthSession :exec
DELETE FROM oauth_sessions WHERE did = $1 AND session_id = $2
`

type DeleteOAuthSessionParams struct {
	Did       string
	SessionID string
}

func (q *Queries) DeleteOAuthSession(ctx context.Context, arg DeleteOAuthSessionParams) error {
	_, err := q.db.Exec(ctx, deleteOAuthSession, arg.Did, arg.SessionID)
	return err
}

const deleteOGCard = `-- name: DeleteOGCard :exec
DELETE FROM og_cards WHERE uri = $1
`

func (q *Queries) DeleteOGCard(ctx context.Context, uri string) error {
	_, err := q.db.Exec(ctx, deleteOGCard, uri)
	return err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles WHERE did = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, did string) error {
	_, err := q.db.Exec(ctx, deleteProfile, did)
	return err
}

const deleteRating = `-- name: DeleteRating :one
DELETE FROM ratings WHERE uri = $1 RETURNING subject_uri
`

func (q *Queries) DeleteRating(ctx context.Context, uri string) (string, error) {
	row := q.db.QueryRow(ctx, deleteRating, uri)
	var subject_uri string
	err := row.Scan(&subject_uri)
	return subject_uri, err
}

const deleteSheet = `-- name: DeleteSheet :one
DELETE FROM sheets WHERE uri = $1 RETURNING fork_of_uri
`

func (q *Queries) DeleteSheet(ctx context.Context, uri string) (string, error) {
	row := q.db.QueryRow(ctx, deleteSheet, uri)
	var fork_of_uri string
	err := row.Scan(&fork_of_uri)
	return fork_of_uri, err
}

const deleteWebSession = `-- name: DeleteWebSession :exec
DELETE FROM web_sessions WHERE token = $1
`

func (q *Queries) DeleteWebSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteWebSession, token)
	return err
}

const deleteWebSessionsBefore = `-- name: DeleteWebSessionsBefore :exec
DELETE FROM web_sessions WHERE created_at < $1
`

func (q *Queries) DeleteWebSessionsBefore(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteWebSessionsBefore, createdAt)
	return err
}

const ensureProfile = `-- name: EnsureProfile :exec
INSERT INTO profiles (did) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) EnsureProfile(ctx context.Context, did string) error {
	_, err := q.db.Exec(ctx, ensureProfile, did)
	return err
}

const favoriteSheets = `-- name: FavoriteSheets :many
SELECT ss.uri, ss.did, ss.rkey, ss.cid, ss.title, ss.artist, ss.album, ss.artist_slug, ss.title_slug, ss.kind, ss.key, ss.capo, ss.tuning, ss.difficulty, ss.tags, ss.fork_of_uri, ss.fork_of_cid, ss.created_at, ss.updated_at, ss.handle, ss.display_name, ss.avatar, ss.rating_count, ss.rating_avg, ss.rating_score, ss.favorite_count, ss.fork_count FROM sheet_summaries ss
JOIN (SELECT fv.subject_uri, MAX(fv.created_at) AS faved_at FROM favorites fv WHERE fv.did = $1 GROUP BY fv.subject_uri) f
    ON f.subject_uri = ss.uri
ORDER BY f.faved_at DESC
`

func (q *Queries) FavoriteSheets(ctx context.Context, did string) ([]SheetSummary, error) {
	rows, err := q.db.Query(ctx, favoriteSheets, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SheetSummary{}
	for rows.Next() {
		var i SheetSummary
		if err := rows.Scan(
			&i.Uri,
			&i.Did,
			&i.Rkey,
			&i.Cid,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.ArtistSlug,
			&i.TitleSlug,
			&i.Kind,
			&i.Key,
			&i.Capo,
			&i.Tuning,
			&i.Difficulty,
			&i.Tags,
			&i.ForkOfUri,
			&i.ForkOfCid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Handle,
			&i.DisplayName,
			&i.Avatar,
			&i.RatingCount,
			&i.RatingAvg,
			&i.RatingScore,
			&i.FavoriteCount,
			&i.ForkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const favoriteSubject = `-- name: FavoriteSubject :one
SELECT subject_uri FROM favorites WHERE uri = $1
`

func (q *Queries) FavoriteSubject(ctx context.Context, uri string) (string, error) {
	row := q.db.QueryRow(ctx, favoriteSubject, uri)
	var subject_uri string
	err := row.Scan(&subject_uri)
	return subject_uri, err
}

const forks = `-- name: Forks :many
SELECT uri, did, rkey, cid, title, artist, album, artist_slug, title_slug, kind, key, capo, tuning, difficulty, tags, fork_of_uri, fork_of_cid, created_at, updated_at, handle, display_name, avatar, rating_count, rating_avg, rating_score, favorite_count, fork_count FROM sheet_summaries WHERE fork_of_uri = $1 ORDER BY rating_score DESC, created_at
`

func (q *Queries) Forks(ctx context.Context, forkOfUri string) ([]SheetSummary, error) {
	rows, err := q.db.Query(ctx, forks, forkOfUri)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SheetSummary{}
	for rows.Next() {
		var i SheetSummary
		if err := rows.Scan(
			&i.Uri,
			&i.Did,
			&i.Rkey,
			&i.Cid,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.ArtistSlug,
			&i.TitleSlug,
			&i.Kind,
			&i.Key,
			&i.Capo,
			&i.Tuning,
			&i.Difficulty,
			&i.Tags,
			&i.ForkOfUri,
			&i.ForkOfCid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Handle,
			&i.DisplayName,
			&i.Avatar,
			&i.RatingCount,
			&i.RatingAvg,
			&i.RatingScore,
			&i.FavoriteCount,
			&i.ForkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOAuthRequest = `-- name: GetOAuthRequest :one
SELECT data FROM oauth_requests WHERE state = $1 AND created_at > $2
`

type GetOAuthRequestParams struct {
	State     string
	CreatedAt time.Time
}

func (q *Queries) GetOAuthRequest(ctx context.Context, arg GetOAuthRequestParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getOAuthRequest, arg.State, arg.CreatedAt)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getOAuthSession = `-- name: GetOAuthSession :one

SELECT data FROM oauth_sessions WHERE did = $1 AND session_id = $2
`

type GetOAuthSessionParams struct {
	Did       string
	SessionID string
}

// OAuth and browser sessions ---------------------------------------------
func (q *Queries) GetOAuthSession(ctx context.Context, arg GetOAuthSessionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getOAuthSession, arg.Did, arg.SessionID)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getOGCard = `-- name: GetOGCard :one

SELECT png FROM og_cards WHERE uri = $1 AND version = $2 AND rendered_at > $3
`

type GetOGCardParams struct {
	Uri        string
	Version    string
	RenderedAt time.Time
}

// Link-preview images -----------------------------------------------------
func (q *Queries) GetOGCard(ctx context.Context, arg GetOGCardParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getOGCard, arg.Uri, arg.Version, arg.RenderedAt)
	var png []byte
	err := row.Scan(&png)
	return png, err
}

const getSheet = `-- name: GetSheet :one
SELECT ss.uri, ss.did, ss.rkey, ss.cid, ss.title, ss.artist, ss.album, ss.artist_slug, ss.title_slug, ss.kind, ss.key, ss.capo, ss.tuning, ss.difficulty, ss.tags, ss.fork_of_uri, ss.fork_of_cid, ss.created_at, ss.updated_at, ss.handle, ss.display_name, ss.avatar, ss.rating_count, ss.rating_avg, ss.rating_score, ss.favorite_count, ss.fork_count, s.content, s.description
FROM sheet_summaries ss JOIN sheets s ON s.uri = ss.uri
WHERE ss.uri = $1
`

type GetSheetRow struct {
	SheetSummary SheetSummary
	Content      string
	Description  string
}

func (q *Queries) GetSheet(ctx context.Context, uri string) (GetSheetRow, error) {
	row := q.db.QueryRow(ctx, getSheet, uri)
	var i GetSheetRow
	err := row.Scan(
		&i.SheetSummary.Uri,
		&i.SheetSummary.Did,
		&i.SheetSummary.Rkey,
		&i.SheetSummary.Cid,
		&i.SheetSummary.Title,
		&i.SheetSummary.Artist,
		&i.SheetSummary.Album,
		&i.SheetSummary.ArtistSlug,
		&i.SheetSummary.TitleSlug,
		&i.SheetSummary.Kind,
		&i.SheetSummary.Key,
		&i.SheetSummary.Capo,
		&i.SheetSummary.Tuning,
		&i.SheetSummary.Difficulty,
		&i.SheetSummary.Tags,
		&i.SheetSummary.ForkOfUri,
		&i.SheetSummary.ForkOfCid,
		&i.SheetSummary.CreatedAt,
		&i.SheetSummary.UpdatedAt,
		&i.SheetSummary.Handle,
		&i.SheetSummary.DisplayName,
		&i.SheetSummary.Avatar,
		&i.SheetSummary.RatingCount,
		&i.SheetSummary.RatingAvg,
		&i.SheetSummary.RatingScore,
		&i.SheetSummary.FavoriteCount,
		&i.SheetSummary.ForkCount,
		&i.Content,
		&i.Description,
	)
	return i, err
}

const getSheetSummary = `-- name: GetSheetSummary :one
SELECT uri, did, rkey, cid, title, artist, album, artist_slug, title_slug, kind, key, capo, tuning, difficulty, tags, fork_of_uri, fork_of_cid, created_at, updated_at, handle, display_name, avatar, rating_count, rating_avg, rating_score, favorite_count, fork_count FROM sheet_summaries WHERE uri = $1
`

func (q *Queries) GetSheetSummary(ctx context.Context, uri string) (SheetSummary, error) {
	row := q.db.QueryRow(ctx, getSheetSummary, uri)
	var i SheetSummary
	err := row.Scan(
		&i.Uri,
		&i.Did,
		&i.Rkey,
		&i.Cid,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.ArtistSlug,
		&i.TitleSlug,
		&i.Kind,
		&i.Key,
		&i.Capo,
		&i.Tuning,
		&i.Difficulty,
		&i.Tags,
		&i.ForkOfUri,
		&i.ForkOfCid,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Handle,
		&i.DisplayName,
		&i.Avatar,
		&i.RatingCount,
		&i.RatingAvg,
		&i.RatingScore,
		&i.FavoriteCount,
		&i.ForkCount,
	)
	return i, err
}

const getState = `-- name: GetState :one
SELECT value FROM ingest_state WHERE name = $1
`

func (q *Queries) GetState(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRow(ctx, getState, name)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getWebSession = `-- name: GetWebSession :one
SELECT did, session_id FROM web_sessions WHERE token = $1 AND created_at > $2
`

type GetWebSessionParams struct {
	Token     string
	CreatedAt time.Time
}

type GetWebSessionRow struct {
	Did       string
	SessionID string
}

func (q *Queries) GetWebSession(ctx context.Context, arg GetWebSessionParams) (GetWebSessionRow, error) {
	row := q.db.QueryRow(ctx, getWebSession, arg.Token, arg.CreatedAt)
	var i GetWebSessionRow
	err := row.Scan(&i.Did, &i.SessionID)
	return i, err
}

const listSheetsRecent = `-- name: ListSheetsRecent :many
SELECT uri, did, rkey, cid, title, artist, album, artist_slug, title_slug, kind, key, capo, tuning, difficulty, tags, fork_of_uri, fork_of_cid, created_at, updated_at, handle, display_name, avatar, rating_count, rating_avg, rating_score, favorite_count, fork_count FROM sheet_summaries ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListSheetsRecentParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListSheetsRecent(ctx context.Context, arg ListSheetsRecentParams) ([]SheetSummary, error) {
	rows, err := q.db.Query(ctx, listSheetsRecent, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SheetSummary{}
	for rows.Next() {
		var i SheetSummary
		if err := rows.Scan(
			&i.Uri,
			&i.Did,
			&i.Rkey,
			&i.Cid,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.ArtistSlug,
			&i.TitleSlug,
			&i.Kind,
			&i.Key,
			&i.Capo,
			&i.Tuning,
			&i.Difficulty,
			&i.Tags,
			&i.ForkOfUri,
			&i.ForkOfCid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Handle,
			&i.DisplayName,
			&i.Avatar,
			&i.RatingCount,
			&i.RatingAvg,
			&i.RatingScore,
			&i.FavoriteCount,
			&i.ForkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSheetsTop = `-- name: ListSheetsTop :many
SELECT uri, did, rkey, cid, title, artist, album, artist_slug, title_slug, kind, key, capo, tuning, difficulty, tags, fork_of_uri, fork_of_cid, created_at, updated_at, handle, display_name, avatar, rating_count, rating_avg, rating_score, favorite_count, fork_count FROM sheet_summaries
ORDER BY rating_score DESC, favorite_count DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListSheetsTopParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListSheetsTop(ctx context.Context, arg ListSheetsTopParams) ([]SheetSummary, error) {
	rows, err := q.db.Query(ctx, listSheetsTop, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SheetSummary{}
	for rows.Next() {
		var i SheetSummary
		if err := rows.Scan(
			&i.Uri,
			&i.Did,
			&i.Rkey,
			&i.Cid,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.ArtistSlug,
			&i.TitleSlug,
			&i.Kind,
			&i.Key,
			&i.Capo,
			&i.Tuning,
			&i.Difficulty,
			&i.Tags,
			&i.ForkOfUri,
			&i.ForkOfCid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Handle,
			&i.DisplayName,
			&i.Avatar,
			&i.RatingCount,
			&i.RatingAvg,
			&i.RatingScore,
			&i.FavoriteCount,
			&i.ForkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProfileStale = `-- name: MarkProfileStale :exec
UPDATE profiles SET resolved_at = NULL WHERE did = $1
`

func (q *Queries) MarkProfileStale(ctx context.Context, did string) error {
	_, err := q.db.Exec(ctx, markProfileStale, did)
	return err
}

const putOGCard = `-- name: PutOGCard :exec
INSERT INTO og_cards (uri, version, png) VALUES ($1, $2, $3)
ON CONFLICT (uri) DO UPDATE SET version = excluded.version, png = excluded.png, rendered_at = now()
`

type PutOGCardParams struct {
	Uri     string
	Version string
	Png     []byte
}

func (q *Queries) PutOGCard(ctx context.Context, arg PutOGCardParams) error {
	_, err := q.db.Exec(ctx, putOGCard, arg.Uri, arg.Version, arg.Png)
	return err
}

const ratingSubject = `-- name: RatingSubject :one
SELECT subject_uri FROM ratings WHERE uri = $1
`

func (q *Queries) RatingSubject(ctx context.Context, uri string) (string, error) {
	row := q.db.QueryRow(ctx, ratingSubject, uri)
	var subject_uri string
	err := row.Scan(&subject_uri)
	return subject_uri, err
}

const recomputeStats = `-- name: RecomputeStats :exec

INSERT INTO sheet_stats (uri, rating_count, rating_avg, rating_score, favorite_count, fork_count)
SELECT $1::text, r.n, COALESCE(r.avg, 0),
    ($2::float8 * $3::float8 + COALESCE(r.total, 0))
        / ($3::float8 + r.n),
    f.n, k.n
FROM
    (SELECT COUNT(*)::int AS n, AVG(value)::float8 AS avg, SUM(value)::float8 AS total
     FROM (SELECT DISTINCT ON (did) value FROM ratings WHERE subject_uri = $1::text
           ORDER BY did, created_at DESC, uri DESC) newest) r,
    (SELECT COUNT(DISTINCT did)::int AS n FROM favorites WHERE subject_uri = $1::text) f,
    (SELECT COUNT(*)::int AS n FROM sheets WHERE fork_of_uri = $1::text) k
ON CONFLICT (uri) DO UPDATE SET
    rating_count = excluded.rating_count, rating_avg = excluded.rating_avg,
    rating_score = excluded.rating_score, favorite_count = excluded.favorite_count,
    fork_count = excluded.fork_count
`

type RecomputeStatsParams struct {
	Uri         string
	PriorMean   float64
	PriorWeight float64
}

// Ratings, favorites, stats ----------------------------------------------
// An account's newest rating of a sheet is the one that counts; the score
// is a Bayesian average toward prior_mean.
func (q *Queries) RecomputeStats(ctx context.Context, arg RecomputeStatsParams) error {
	_, err := q.db.Exec(ctx, recomputeStats, arg.Uri, arg.PriorMean, arg.PriorWeight)
	return err
}

const saveOAuthRequest = `-- name: SaveOAuthRequest :exec
INSERT INTO oauth_requests (state, data) VALUES ($1, $2)
`

type SaveOAuthRequestParams struct {
	State string
	Data  []byte
}

func (q *Queries) SaveOAuthRequest(ctx context.Context, arg SaveOAuthRequestParams) error {
	_, err := q.db.Exec(ctx, saveOAuthRequest, arg.State, arg.Data)
	return err
}

const saveOAuthSession = `-- name: SaveOAuthSession :exec
INSERT INTO oauth_sessions (did, session_id, data) VALUES ($1, $2, $3)
ON CONFLICT (did, session_id) DO UPDATE SET data = excluded.data, updated_at = now()
`

type SaveOAuthSessionParams struct {
	Did       string
	SessionID string
	Data      []byte
}

func (q *Queries) SaveOAuthSession(ctx context.Context, arg SaveOAuthSessionParams) error {
	_, err := q.db.Exec(ctx, saveOAuthSession, arg.Did, arg.SessionID, arg.Data)
	return err
}

const searchSheets = `-- name: SearchSheets :many
WITH q AS (SELECT to_tsquery('simple', $1::text) AS query),
hits AS (
    SELECT s.uri,
        (CASE WHEN to_tsvector('simple', s.names) @@ q.query THEN 4 ELSE 0 END)
            + 2 * GREATEST(word_similarity($2::text, s.names),
                           word_similarity($3::text, s.names_compact))
            + ts_rank(s.search, q.query) AS rank,
        CASE WHEN to_tsvector('simple', s.lyrics) @@ q.query
            THEN ts_headline('simple', s.lyrics, q.query, $4::text)
            ELSE '' END AS snip
    FROM sheets s, q
    WHERE s.search @@ q.query
        OR $2::text <% s.names
        OR $3::text <% s.names_compact
    ORDER BY rank DESC
    LIMIT 500
)
SELECT ss.uri, ss.did, ss.rkey, ss.cid, ss.title, ss.artist, ss.album, ss.artist_slug, ss.title_slug, ss.kind, ss.key, ss.capo, ss.tuning, ss.difficulty, ss.tags, ss.fork_of_uri, ss.fork_of_cid, ss.created_at, ss.updated_at, ss.handle, ss.display_name, ss.avatar, ss.rating_count, ss.rating_avg, ss.rating_score, ss.favorite_count, ss.fork_count, h.snip::text AS snippet
FROM hits h JOIN sheet_summaries ss ON ss.uri = h.uri
ORDER BY h.rank DESC
`

type SearchSheetsParams struct {
	Query        string
	Plain        string
	Compact      string
	HeadlineOpts string
}

type SearchSheetsRow struct {
	SheetSummary SheetSummary
	Snippet      string
}

// Every word must match (the last as a prefix), or the names must be a
// near miss, spaced or not ("deathcab", "death cab"). A title or artist
// match always outranks a lyrics-only one: it gets a flat bonus, and
// ts_rank's lyric weight is tiny so a word repeated through a chorus
// can't pile up past it.
func (q *Queries) SearchSheets(ctx context.Context, arg SearchSheetsParams) ([]SearchSheetsRow, error) {
	rows, err := q.db.Query(ctx, searchSheets,
		arg.Query,
		arg.Plain,
		arg.Compact,
		arg.HeadlineOpts,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSheetsRow{}
	for rows.Next() {
		var i SearchSheetsRow
		if err := rows.Scan(
			&i.SheetSummary.Uri,
			&i.SheetSummary.Did,
			&i.SheetSummary.Rkey,
			&i.SheetSummary.Cid,
			&i.SheetSummary.Title,
			&i.SheetSummary.Artist,
			&i.SheetSummary.Album,
			&i.SheetSummary.ArtistSlug,
			&i.SheetSummary.TitleSlug,
			&i.SheetSummary.Kind,
			&i.SheetSummary.Key,
			&i.SheetSummary.Capo,
			&i.SheetSummary.Tuning,
			&i.SheetSummary.Difficulty,
			&i.SheetSummary.Tags,
			&i.SheetSummary.ForkOfUri,
			&i.SheetSummary.ForkOfCid,
			&i.SheetSummary.CreatedAt,
			&i.SheetSummary.UpdatedAt,
			&i.SheetSummary.Handle,
			&i.SheetSummary.DisplayName,
			&i.SheetSummary.Avatar,
			&i.SheetSummary.RatingCount,
			&i.SheetSummary.RatingAvg,
			&i.SheetSummary.RatingScore,
			&i.SheetSummary.FavoriteCount,
			&i.SheetSummary.ForkCount,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setHidden = `-- name: SetHidden :exec
UPDATE profiles SET hidden = $2 WHERE did = $1 AND hidden <> $2
`

type SetHiddenParams struct {
	Did    string
	Hidden bool
}

func (q *Queries) SetHidden(ctx context.Context, arg SetHiddenParams) error {
	_, err := q.db.Exec(ctx, setHidden, arg.Did, arg.Hidden)
	return err
}

const setState = `-- name: SetState :exec
INSERT INTO ingest_state (name, value) VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE SET value = excluded.value
`

type SetStateParams struct {
	Name  string
	Value string
}

func (q *Queries) SetState(ctx context.Context, arg SetStateParams) error {
	_, err := q.db.Exec(ctx, setState, arg.Name, arg.Value)
	return err
}

const sheetForkOf = `-- name: SheetForkOf :one


SELECT fork_of_uri FROM sheets WHERE uri = $1
`

// Queries for sqlc (`just sqlc` regenerates pkg/store/dbq).
// Sheets ----------------------------------------------------------------
func (q *Queries) SheetForkOf(ctx context.Context, uri string) (string, error) {
	row := q.db.QueryRow(ctx, sheetForkOf, uri)
	var fork_of_uri string
	err := row.Scan(&fork_of_uri)
	return fork_of_uri, err
}

const sheetsByDID = `-- name: SheetsByDID :many
SELECT uri, did, rkey, cid, title, artist, album, artist_slug, title_slug, kind, key, capo, tuning, difficulty, tags, fork_of_uri, fork_of_cid, created_at, updated_at, handle, display_name, avatar, rating_count, rating_avg, rating_score, favorite_count, fork_count FROM sheet_summaries WHERE did = $1 ORDER BY created_at DESC
`

func (q *Queries) SheetsByDID(ctx context.Context, did string) ([]SheetSummary, error) {
	rows, err := q.db.Query(ctx, sheetsByDID, did)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SheetSummary{}
	for rows.Next() {
		var i SheetSummary
		if err := rows.Scan(
			&i.Uri,
			&i.Did,
			&i.Rkey,
			&i.Cid,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.ArtistSlug,
			&i.TitleSlug,
			&i.Kind,
			&i.Key,
			&i.Capo,
			&i.Tuning,
			&i.Difficulty,
			&i.Tags,
			&i.ForkOfUri,
			&i.ForkOfCid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Handle,
			&i.DisplayName,
			&i.Avatar,
			&i.RatingCount,
			&i.RatingAvg,
			&i.RatingScore,
			&i.FavoriteCount,
			&i.ForkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sheetsByKind = `-- name: SheetsByKind :many
SELECT s.kind, COUNT(*)::bigint AS n FROM sheets s GROUP BY s.kind
`

type SheetsByKindRow struct {
	Kind string
	N    int64
}

func (q *Queries) SheetsByKind(ctx context.Context) ([]SheetsByKindRow, error) {
	rows, err := q.db.Query(ctx, sheetsByKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SheetsByKindRow{}
	for rows.Next() {
		var i SheetsByKindRow
		if err := rows.Scan(&i.Kind, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const songSheets = `-- name: SongSheets :many
SELECT uri, did, rkey, cid, title, artist, album, artist_slug, title_slug, kind, key, capo, tuning, difficulty, tags, fork_of_uri, fork_of_cid, created_at, updated_at, handle, display_name, avatar, rating_count, rating_avg, rating_score, favorite_count, fork_count FROM sheet_summaries WHERE artist_slug = $1 AND title_slug = $2 ORDER BY created_at, uri
`

type SongSheetsParams struct {
	ArtistSlug string
	TitleSlug  string
}

func (q *Queries) SongSheets(ctx context.Context, arg SongSheetsParams) ([]SheetSummary, error) {
	rows, err := q.db.Query(ctx, songSheets, arg.ArtistSlug, arg.TitleSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SheetSummary{}
	for rows.Next() {
		var i SheetSummary
		if err := rows.Scan(
			&i.Uri,
			&i.Did,
			&i.Rkey,
			&i.Cid,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.ArtistSlug,
			&i.TitleSlug,
			&i.Kind,
			&i.Key,
			&i.Capo,
			&i.Tuning,
			&i.Difficulty,
			&i.Tags,
			&i.ForkOfUri,
			&i.ForkOfCid,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Handle,
			&i.DisplayName,
			&i.Avatar,
			&i.RatingCount,
			&i.RatingAvg,
			&i.RatingScore,
			&i.FavoriteCount,
			&i.ForkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const staleProfiles = `-- name: StaleProfiles :many
SELECT did FROM profiles
WHERE resolved_at IS NULL OR resolved_at < $1
ORDER BY resolved_at NULLS FIRST
LIMIT $2
`

type StaleProfilesParams struct {
	ResolvedAt *time.Time
	Limit      int32
}

func (q *Queries) StaleProfiles(ctx context.Context, arg StaleProfilesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, staleProfiles, arg.ResolvedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var did string
		if err := rows.Scan(&did); err != nil {
			return nil, err
		}
		items = append(items, did)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFavorite = `-- name: UpsertFavorite :exec
INSERT INTO favorites (uri, did, subject_uri, subject_cid, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (uri) DO UPDATE SET subject_uri = excluded.subject_uri,
    subject_cid = excluded.subject_cid, created_at = excluded.created_at
`

type UpsertFavoriteParams struct {
	Uri        string
	Did        string
	SubjectUri string
	SubjectCid string
	CreatedAt  time.Time
}

func (q *Queries) UpsertFavorite(ctx context.Context, arg UpsertFavoriteParams) error {
	_, err := q.db.Exec(ctx, upsertFavorite,
		arg.Uri,
		arg.Did,
		arg.SubjectUri,
		arg.SubjectCid,
		arg.CreatedAt,
	)
	return err
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO profiles (did, handle, display_name, avatar, resolved_at) VALUES ($1, $2, $3, $4, now())
ON CONFLICT (did) DO UPDATE SET handle = excluded.handle, display_name = excluded.display_name,
    avatar = excluded.avatar, resolved_at = excluded.resolved_at
`

type UpsertProfileParams struct {
	Did         string
	Handle      string
	DisplayName string
	Avatar      string
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.Exec(ctx, upsertProfile,
		arg.Did,
		arg.Handle,
		arg.DisplayName,
		arg.Avatar,
	)
	return err
}

const upsertRating = `-- name: UpsertRating :exec
INSERT INTO ratings (uri, did, subject_uri, subject_cid, value, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (uri) DO UPDATE SET subject_uri = excluded.subject_uri,
    subject_cid = excluded.subject_cid, value = excluded.value, created_at = excluded.created_at
`

type UpsertRatingParams struct {
	Uri        string
	Did        string
	SubjectUri string
	SubjectCid string
	Value      int32
	CreatedAt  time.Time
}

func (q *Queries) UpsertRating(ctx context.Context, arg UpsertRatingParams) error {
	_, err := q.db.Exec(ctx, upsertRating,
		arg.Uri,
		arg.Did,
		arg.SubjectUri,
		arg.SubjectCid,
		arg.Value,
		arg.CreatedAt,
	)
	return err
}

const upsertSheet = `-- name: UpsertSheet :exec
INSERT INTO sheets (uri, did, rkey, cid, title, artist, album, artist_slug, title_slug,
    kind, key, capo, tuning, difficulty, description, tags, tags_text, content, lyrics,
    fork_of_uri, fork_of_cid, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16, $17, $18, $19,
    $20, $21, $22, $23)
ON CONFLICT (uri) DO UPDATE SET
    cid = excluded.cid, title = excluded.title, artist = excluded.artist, album = excluded.album,
    artist_slug = excluded.artist_slug, title_slug = excluded.title_slug, kind = excluded.kind,
    key = excluded.key, capo = excluded.capo, tuning = excluded.tuning,
    difficulty = excluded.difficulty, description = excluded.description, tags = excluded.tags,
    tags_text = excluded.tags_text, content = excluded.content, lyrics = excluded.lyrics,
    fork_of_uri = excluded.fork_of_uri, fork_of_cid = excluded.fork_of_cid,
    created_at = excluded.created_at, updated_at = excluded.updated_at, indexed_at = now()
`

type UpsertSheetParams struct {
	Uri         string
	Did         string
	Rkey        string
	Cid         string
	Title       string
	Artist      string
	Album       string
	ArtistSlug  string
	TitleSlug   string
	Kind        string
	Key         string
	Capo        int32
	Tuning      string
	Difficulty  string
	Description string
	Tags        []string
	TagsText    string
	Content     string
	Lyrics      string
	ForkOfUri   string
	ForkOfCid   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpsertSheet(ctx context.Context, arg UpsertSheetParams) error {
	_, err := q.db.Exec(ctx, upsertSheet,
		arg.Uri,
		arg.Did,
		arg.Rkey,
		arg.Cid,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.ArtistSlug,
		arg.TitleSlug,
		arg.Kind,
		arg.Key,
		arg.Capo,
		arg.Tuning,
		arg.Difficulty,
		arg.Description,
		arg.Tags,
		arg.TagsText,
		arg.Content,
		arg.Lyrics,
		arg.ForkOfUri,
		arg.ForkOfCid,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const usageStats = `-- name: UsageStats :one

SELECT
    (SELECT COUNT(*) FROM sheets s1)::bigint AS sheets,
    (SELECT COUNT(DISTINCT s2.did) FROM sheets s2)::bigint AS authors,
    (SELECT COUNT(*) FROM sheets s3 WHERE s3.created_at > now() - interval '24 hours')::bigint AS sheets_24h,
    (SELECT COUNT(*) FROM (SELECT DISTINCT r.did, r.subject_uri FROM ratings r) rr)::bigint AS ratings,
    (SELECT COUNT(*) FROM (SELECT DISTINCT f.did, f.subject_uri FROM favorites f) ff)::bigint AS favorites,
    (SELECT COUNT(*) FROM profiles p)::bigint AS accounts,
    (SELECT COUNT(DISTINCT w.did) FROM web_sessions w WHERE w.created_at > $1::timestamptz)::bigint AS signed_in_accounts,
    (SELECT COUNT(*) FROM og_cards o)::bigint AS og_cards,
    pg_database_size(current_database())::bigint AS db_size_bytes
`

type UsageStatsRow struct {
	Sheets           int64
	Authors          int64
	Sheets24h        int64
	Ratings          int64
	Favorites        int64
	Accounts         int64
	SignedInAccounts int64
	OgCards          int64
	DbSizeBytes      int64
}

// Usage gauges (see metrics.Collector) ------------------------------------
func (q *Queries) UsageStats(ctx context.Context, sessionCutoff time.Time) (UsageStatsRow, error) {
	row := q.db.QueryRow(ctx, usageStats, sessionCutoff)
	var i UsageStatsRow
	err := row.Scan(
		&i.Sheets,
		&i.Authors,
		&i.Sheets24h,
		&i.Ratings,
		&i.Favorites,
		&i.Accounts,
		&i.SignedInAccounts,
		&i.OgCards,
		&i.DbSizeBytes,
	)
	return i, err
}

const viewerFavorites = `-- name: ViewerFavorites :many
SELECT uri FROM favorites WHERE did = $1 AND subject_uri = $2
`

type ViewerFavoritesParams struct {
	Did        string
	SubjectUri string
}

func (q *Queries) ViewerFavorites(ctx context.Context, arg ViewerFavoritesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, viewerFavorites, arg.Did, arg.SubjectUri)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var uri string
		if err := rows.Scan(&uri); err != nil {
			return nil, err
		}
		items = append(items, uri)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const viewerRatings = `-- name: ViewerRatings :many
SELECT uri, value FROM ratings WHERE did = $1 AND subject_uri = $2 ORDER BY created_at DESC, uri DESC
`

type ViewerRatingsParams struct {
	Did        string
	SubjectUri string
}

type ViewerRatingsRow struct {
	Uri   string
	Value int32
}

func (q *Queries) ViewerRatings(ctx context.Context, arg ViewerRatingsParams) ([]ViewerRatingsRow, error) {
	rows, err := q.db.Query(ctx, viewerRatings, arg.Did, arg.SubjectUri)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ViewerRatingsRow{}
	for rows.Next() {
		var i ViewerRatingsRow
		if err := rows.Scan(&i.Uri, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
